# Generated by Django 3.0.4 on 2021-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesture', '0002_auto_20210215_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestureimage',
            name='time',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
